name: This is it
on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
jobs:
  checks:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn danger ci
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_API_TOKEN }}